# Generated by Django 5.2.17 on 2026-09-24 12:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('consent', models.BooleanField(default=False, verbose_name='Згода на обробку даних')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='network.city', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, max_length=80, verbose_name='Месенджер')),
                ('board', models.CharField(choices=[('retail', 'Роздріб'), ('wholesale', 'Опт'), ('cross', 'Крос'), ('crypto', 'Крипто')], default='retail', max_length=16, verbose_name='Дошка')),
                ('direction', models.CharField(choices=[('buy', 'Купити'), ('sell', 'Продати')], max_length=8, verbose_name='Напрямок')),
                ('amount_give', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Віддаєте')),
                ('amount_receive', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Отримуєте')),
                ('rate_fixed', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Зафіксований курс')),
                ('consent', models.BooleanField(default=False, verbose_name='Згода на обробку даних')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('done', 'Виконана'), ('expired', 'Прострочена'), ('cancelled', 'Скасована')], default='new', max_length=16, verbose_name='Статус')),
                ('expires_at', models.DateTimeField(verbose_name='Дійсна до')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to='network.branch', verbose_name='Відділення')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to='network.city', verbose_name='Місто')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='rates.currencypair', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'Заявка на обмін',
                'verbose_name_plural': 'Заявки на обмін',
                'ordering': ['-created_at'],
            },
        ),
    ]
