# Generated by Django 5.2.17 on 2026-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('telegram', 'Telegram')], default='web', max_length=16, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telegram chat id'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('telegram', 'Telegram')], default='web', max_length=16, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telegram chat id'),
        ),
    ]
