# Generated by Django 5.2.17 on 2026-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('citizens', 'Городянам'), ('guests', 'Гостям міста'), ('business', 'Бізнесменам')], max_length=16, verbose_name='Аудиторія')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Пункт переваги',
                'verbose_name_plural': 'Пункти переваг',
                'ordering': ['audience', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvantagesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Переваги', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступ')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Сторінка переваг',
                'verbose_name_plural': 'Сторінка переваг',
            },
        ),
        migrations.CreateModel(
            name='CitiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Міста мережі', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступ')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Сторінка міст',
                'verbose_name_plural': 'Сторінка міст',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакти', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступ')),
                ('map_image', models.ImageField(blank=True, upload_to='contacts/', verbose_name='Зображення карти')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Сторінка контактів',
                'verbose_name_plural': 'Сторінка контактів',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('banner_exchange', models.ImageField(blank=True, upload_to='home/', verbose_name='Банер після курсів')),
                ('banner_service', models.ImageField(blank=True, upload_to='home/', verbose_name='Банер після послуг')),
                ('banner_cta', models.ImageField(blank=True, upload_to='home/', verbose_name='Банер CTA')),
                ('cta_title', models.CharField(default='Зафіксуй курс. Забронюй онлайн.', max_length=160, verbose_name='CTA заголовок')),
                ('seo_block_title', models.CharField(default='Обмін валют', max_length=160, verbose_name='SEO блок · заголовок')),
                ('seo_block_body', models.TextField(blank=True, verbose_name='SEO блок · текст')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Політика конфіденційності', max_length=160, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Політика конфіденційності',
                'verbose_name_plural': 'Політика конфіденційності',
            },
        ),
        migrations.CreateModel(
            name='RatesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Курси валют', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступ')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Сторінка курсів',
                'verbose_name_plural': 'Сторінка курсів',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('short_desc', models.TextField(verbose_name='Короткий опис')),
                ('body', models.TextField(blank=True, verbose_name='Повний опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Послуги', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступ')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Сторінка послуг',
                'verbose_name_plural': 'Сторінка послуг',
            },
        ),
    ]
