# Generated by Django 6.0.1 on 2026-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_advantageitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Політика використання файлів Cookie', max_length=160, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Політика Cookie',
                'verbose_name_plural': 'Політика Cookie',
            },
        ),
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Публічна оферта', max_length=160, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Публічна оферта',
                'verbose_name_plural': 'Публічна оферта',
            },
        ),
    ]
