# Generated by Django 5.2.17 on 2026-10-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_legal_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону')),
                ('color_text', models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту')),
                ('color_accent', models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки')),
                ('title', models.CharField(default='Блог', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступний текст')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку')),
            ],
            options={
                'verbose_name': 'Сторінка блогу',
                'verbose_name_plural': 'Сторінка блогу',
            },
        ),
        migrations.CreateModel(
            name='ReviewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону')),
                ('color_text', models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту')),
                ('color_accent', models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки')),
                ('title', models.CharField(default='Відгуки', max_length=120, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступний текст')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку')),
            ],
            options={
                'verbose_name': 'Сторінка відгуків',
                'verbose_name_plural': 'Сторінка відгуків',
            },
        ),
        migrations.AlterModelOptions(
            name='cookiepage',
            options={'verbose_name': 'Політика файлів cookie', 'verbose_name_plural': 'Політика файлів cookie'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Питання і відповідь', 'verbose_name_plural': 'Питання і відповіді'},
        ),
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'Сторінка частих питань', 'verbose_name_plural': 'Сторінка частих питань'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Картка послуги', 'verbose_name_plural': 'Картки послуг'},
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='citiespage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='citiespage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='citiespage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='cookiepage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='cookiepage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='cookiepage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='ratespage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='ratespage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='ratespage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='audience',
            field=models.CharField(choices=[('citizens', 'Городянам'), ('guests', 'Гостям міста'), ('business', 'Бізнесменам')], max_length=16, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='advantageitem',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Заголовок пункту'),
        ),
        migrations.AlterField(
            model_name='advantagespage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='advantagespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='advantagespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='citiespage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='citiespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='citiespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='cookiepage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст сторінки'),
        ),
        migrations.AlterField(
            model_name='cookiepage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='cookiepage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='title',
            field=models.CharField(default='Часті питання', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_cta',
            field=models.ImageField(blank=True, upload_to='home/', verbose_name='Банер із закликом залишити заявку'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_exchange',
            field=models.ImageField(blank=True, upload_to='home/', verbose_name='Банер після блоків курсів'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_service',
            field=models.ImageField(blank=True, upload_to='home/', verbose_name='Банер після блоку послуг'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(default='Зафіксуй курс. Забронюй онлайн.', max_length=160, verbose_name='Заголовок банера із закликом'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_block_body',
            field=models.TextField(blank=True, verbose_name='Текст інформаційного блоку'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_block_title',
            field=models.CharField(default='Обмін валют', max_length=160, verbose_name='Заголовок інформаційного блоку'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст сторінки'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст сторінки'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='ratespage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='ratespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='ratespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='Адреса сторінки'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
    ]
