# Generated by Django 5.2.17 on 2026-10-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cms_page_sections'),
        ('content', '0008_home_promo_services_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeArticlesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Корисні статті',
                'verbose_name_plural': 'Корисні статті',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomeCalcSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Розрахунок обміну',
                'verbose_name_plural': 'Розрахунок обміну',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomeFaqSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Відповіді на поширені запитання',
                'verbose_name_plural': 'Відповіді на поширені запитання',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomePromoSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Вигідний курс',
                'verbose_name_plural': 'Вигідний курс',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomeReviewsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Відгуки на головній',
                'verbose_name_plural': 'Відгуки на головній',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomeSearchSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Пошук головної',
                'verbose_name_plural': 'Пошук головної',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomeServicesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Наші послуги',
                'verbose_name_plural': 'Наші послуги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.CreateModel(
            name='HomeWhySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Чому нас обирають',
                'verbose_name_plural': 'Чому нас обирають',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.homepage',),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='branches_kicker',
            field=models.CharField(default='Відділення', max_length=80, verbose_name='Підпис блоку відділень'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='branches_title',
            field=models.CharField(default='Відділення', max_length=120, verbose_name='Заголовок блоку відділень'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='branches_title_accent',
            field=models.CharField(default='по Україні', max_length=80, verbose_name='Акцент блоку відділень'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='email',
            field=models.CharField(default='info@obmin21.ua', max_length=80, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='email_hint',
            field=models.CharField(default='Для співпраці та бізнес-клієнтів', max_length=80, verbose_name='Підказка до email'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='hours',
            field=models.CharField(default='Пн–Нд, 8:00–21:00', max_length=80, verbose_name='Графік роботи'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='hours_hint',
            field=models.CharField(default='Без перерв і вихідних', max_length=80, verbose_name='Підказка до графіка'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='phone',
            field=models.CharField(default='+38(044)444 44 44', max_length=40, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='phone_hint',
            field=models.CharField(default='Щодня з 8:00 до 21:00', max_length=80, verbose_name='Підказка до телефону'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='telegram',
            field=models.CharField(default='@obmin21', max_length=80, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='telegram_hint',
            field=models.CharField(default='Відповідаємо за кілька хвилин', max_length=80, verbose_name='Підказка до Telegram'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='title_accent',
            field=models.CharField(default='з нами', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='content.homepage', verbose_name='Головна'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='articles_kicker',
            field=models.CharField(default='Статті', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='articles_lead',
            field=models.CharField(default='Окрім обміну валют у мережі Обмін21 доступні грошові перекази по Україні, міжнародні перекази та обмін електронних валют — умови та підготовка до візиту нижче.', max_length=400, verbose_name='Текст під заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='articles_title',
            field=models.CharField(default='Корисні', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='articles_title_accent',
            field=models.CharField(default='статті', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_amount',
            field=models.CharField(default='1000', max_length=16, verbose_name='Сума за замовчуванням'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_button',
            field=models.CharField(default='Забронювати заявку', max_length=80, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_get',
            field=models.CharField(default='Отримую', max_length=40, verbose_name='Підпис «Отримую»'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_give',
            field=models.CharField(default='Віддаю', max_length=40, verbose_name='Підпис «Віддаю»'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_kicker',
            field=models.CharField(default='Калькулятор', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_lead',
            field=models.CharField(default='Дізнайтесь, скільки ви отримаєте та зафіксуйте курс онлайн', max_length=240, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_lock',
            field=models.CharField(default='Курс діє 30 хв', max_length=80, verbose_name='Підпис під кнопкою'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_rate_hint',
            field=models.CharField(default='За поточним курсом', max_length=80, verbose_name='Підказка курсу'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_title',
            field=models.CharField(default='Розрахуйте', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calc_title_accent',
            field=models.CharField(default='обмін', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_kicker',
            field=models.CharField(default='Відповіді', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_title',
            field=models.CharField(default='Відповіді на', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_title_accent',
            field=models.CharField(default='поширені запитання', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_posts',
            field=models.ManyToManyField(blank=True, help_text='Якщо порожньо — показуємо останні опубліковані.', related_name='home_features', to='blog.post', verbose_name='Статті на головній'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_address_label',
            field=models.CharField(default='Адреса:', max_length=40, verbose_name='Підпис адреси'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_button',
            field=models.CharField(default='Відкрити в Google Maps', max_length=80, verbose_name='Текст кнопки карти'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_hours_label',
            field=models.CharField(default='Графік:', max_length=40, verbose_name='Підпис графіка'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_kicker',
            field=models.CharField(default='Відділення', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_phone_label',
            field=models.CharField(default='Телефон:', max_length=40, verbose_name='Підпис телефону'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_title',
            field=models.CharField(default='Знайдіть нас', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_title_accent',
            field=models.CharField(default='на карті', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_kicker',
            field=models.CharField(default='Відгуки', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_title',
            field=models.CharField(default='Відгуки', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_kicker',
            field=models.CharField(default='Послуги', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_lead',
            field=models.CharField(default='Окрім обміну валют у мережі Обмін21 доступні грошові перекази по Україні, міжнародні перекази та обмін електронних валют — умови та підготовка до візиту нижче.', max_length=400, verbose_name='Текст під заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Наші', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title_accent',
            field=models.CharField(default='послуги', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_kicker',
            field=models.CharField(default='Переваги', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_title',
            field=models.CharField(default='Чому нас', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_title_accent',
            field=models.CharField(default='обирають', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='service',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cards', to='content.homepage', verbose_name='Головна'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='Фото картки'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_on_home',
            field=models.BooleanField(default=True, verbose_name='Показувати на головній'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='intro',
            field=models.TextField(blank=True, default='Відповімо на питання, підкажемо курс і допоможемо забронювати обмін у зручному відділенні.', verbose_name='Вступний текст'),
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Цифра')),
                ('text', models.TextField(verbose_name='Текст картки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.homepage', verbose_name='Головна')),
            ],
            options={
                'verbose_name': 'Картка «Чому нас обирають»',
                'verbose_name_plural': 'Картки «Чому нас обирають»',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
