# Generated by Django 5.2.17 on 2026-10-06 08:05

from django.db import migrations, models

INTRO = (
    'Пояснюємо, як працює курс валют, як зберегти заощадження '
    'та безпечно обміняти гроші.'
)


def fill_blog_page(apps, schema_editor):
    BlogPage = apps.get_model('content', 'BlogPage')
    for page in BlogPage.objects.all():
        changed = False
        if not page.heading:
            page.heading = 'Корисні'
            changed = True
        if not page.title_accent:
            page.title_accent = 'статті'
            changed = True
        if not (page.intro or '').strip():
            page.intro = INTRO
            changed = True
        if changed:
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_seed_home_section_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Сторінка Блог', 'verbose_name_plural': 'Сторінка Блог'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='heading',
            field=models.CharField(default='Корисні', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='title_accent',
            field=models.CharField(default='статті', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(blank=True, default='Пояснюємо, як працює курс валют, як зберегти заощадження та безпечно обміняти гроші.', verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='title',
            field=models.CharField(default='Блог', max_length=120, verbose_name='Мітка'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='email',
            field=models.CharField(default='info@obmin21.ua', max_length=80, verbose_name='Електронна пошта'),
        ),
        migrations.RunPython(fill_blog_page, migrations.RunPython.noop),
    ]
