# Generated by Django 5.2.17 on 2026-10-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_blog_page_heading_and_category_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='heading',
            field=models.CharField(default='Зв’яжіться', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Вступний текст'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='title',
            field=models.CharField(default='Контакти', max_length=120, verbose_name='Мітка'),
        ),
    ]
