# Generated by Django 5.2.17 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contacts_heading_and_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantagespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='advantagespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='citiespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='citiespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='cookiepage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='cookiepage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='ratespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='ratespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='reviewspage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='reviewspage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
    ]
