# Generated by Django 5.2.17 on 2026-10-06 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_service_short_desc_plain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesearchsettings',
            options={'verbose_name': 'Оформлення головної', 'verbose_name_plural': 'Оформлення головної'},
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='cmp_btn',
            field=models.CharField(default='Зафіксувати курс', max_length=80, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='cmp_kicker',
            field=models.CharField(default='Порівняння', max_length=80, verbose_name='Підпис блоку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='cmp_them_html',
            field=models.TextField(default='<ul><li><span>Курс</span><strong>Курс банку з націнкою</strong></li><li><span>Комісія</span><strong>Від 1 до 3%</strong></li><li><span>Фіксація курсу</span><strong>Лише у відділенні</strong></li><li><span>Зношені купюри</span><strong>Часто відмовляють</strong></li><li><span>Криптовалюта</span><strong>Недоступно</strong></li><li><span>Великі суми</span><strong>Стандартні умови</strong></li></ul>', verbose_name='Список «Інші обмінники»'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='cmp_title',
            field=models.CharField(default='Обмін21 чи', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='cmp_title_accent',
            field=models.CharField(default='звичайний обмінник', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='cmp_us_html',
            field=models.TextField(default='<ul><li><span>Курс</span><strong>Кращий за банківський</strong></li><li><span>Комісія</span><strong>0 ₴ за будь-яку суму</strong></li><li><span>Фіксація курсу</span><strong>Онлайн на 30 хвилин</strong></li><li><span>Зношені купюри</span><strong>Приймаємо та обмінюємо</strong></li><li><span>Криптовалюта</span><strong>USDT, BTC, ETH на готівку</strong></li><li><span>Великі суми</span><strong>Індивідуальний курс</strong></li></ul>', verbose_name='Список «Рекомендуємо»'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='color_hero_bg',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону банера'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='color_why_banner',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон банера'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_banner',
            field=models.ImageField(blank=True, upload_to='advantages/', verbose_name='Фото банера'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_btn_primary',
            field=models.CharField(default='Забронювати заявку', max_length=80, verbose_name='Кнопка 1'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_btn_secondary',
            field=models.CharField(default='Усі переваги', max_length=80, verbose_name='Кнопка 2'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_cards_image',
            field=models.ImageField(blank=True, upload_to='advantages/', verbose_name='Картинка карток'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_kicker',
            field=models.CharField(default='Переваги', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_lead',
            field=models.TextField(default='Вигідний курс без комісій, фіксація онлайн і перевірка кожної купюри. Ось що цінують наші клієнти.', verbose_name='Підзаголовок банера'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_title',
            field=models.CharField(default='Чому обирають', max_length=120, verbose_name='Заголовок банера'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='hero_title_accent',
            field=models.CharField(default='Обмін21', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_1_text',
            field=models.TextField(default='Постійних клієнтів — нам довіряють тисячі людей, які обирають нас для швидкого та зручного обміну валют і криптоактивів', verbose_name='Перевага 1 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_1_title',
            field=models.CharField(default='7K', max_length=40, verbose_name='Перевага 1 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_2_text',
            field=models.TextField(default='Відділень в Україні — обмінюйте валюту у зручному для вас відділенні та отримуйте якісний сервіс', verbose_name='Перевага 2 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_2_title',
            field=models.CharField(default='20+', max_length=40, verbose_name='Перевага 2 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_3_text',
            field=models.TextField(default='Прозорість обміну — жодних прихованих платежів: ви заздалегідь бачите актуальний курс та умови операції', verbose_name='Перевага 3 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_3_title',
            field=models.CharField(default='100%', max_length=40, verbose_name='Перевага 3 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_4_text',
            field=models.TextField(default='Років досвіду — понад 10 років ми працюємо у сфері обміну, забезпечуючи стабільність, професійність та прозорі умови', verbose_name='Перевага 4 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stat_4_title',
            field=models.CharField(default='10+', max_length=40, verbose_name='Перевага 4 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stats_kicker',
            field=models.CharField(default='Цифри', max_length=80, verbose_name='Підпис блоку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stats_title',
            field=models.CharField(default='Обмін21', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='stats_title_accent',
            field=models.CharField(default='у цифрах', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_1_text',
            field=models.TextField(default='Сума в калькуляторі дорівнює сумі, яку ви отримаєте на руки', verbose_name='Перевага 1 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_1_title',
            field=models.CharField(default='Жодних комісій', max_length=120, verbose_name='Перевага 1 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_2_text',
            field=models.TextField(default='Забронюйте курс онлайн і приходьте без ризику, що він зміниться дорогою', verbose_name='Перевага 2 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_2_title',
            field=models.CharField(default='Фіксація курсу на 30 хвилин', max_length=120, verbose_name='Перевага 2 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_3_text',
            field=models.TextField(default='Детектори валют у кожному відділенні: видаємо лише справні банкноти', verbose_name='Перевага 3 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_3_title',
            field=models.CharField(default='Перевірка кожної купюри', max_length=120, verbose_name='Перевага 3 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_4_text',
            field=models.TextField(default='Окрема зона для великих сум, дані клієнтів під захистом', verbose_name='Перевага 4 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_4_title',
            field=models.CharField(default='Конфіденційно і безпечно', max_length=120, verbose_name='Перевага 4 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_5_text',
            field=models.TextField(default='Відділення в 11 містах України з розширеним графіком роботи', verbose_name='Перевага 5 — підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_5_title',
            field=models.CharField(default='Поруч з вами', max_length=120, verbose_name='Перевага 5 — заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_banner',
            field=models.ImageField(blank=True, upload_to='advantages/', verbose_name='Банер блоку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_banner_accent',
            field=models.CharField(default='ніж у банку', max_length=80, verbose_name='Акцент на банері'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_banner_text',
            field=models.TextField(default='Щодня порівнюємо курси з ринком і тримаємо різницю між купівлею та продажем мінімальною.', verbose_name='Текст на банері'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_banner_title',
            field=models.CharField(default='Курс кращий,', max_length=120, verbose_name='Заголовок на банері'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_coins',
            field=models.ImageField(blank=True, upload_to='advantages/', verbose_name='Картинка монет'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_kicker',
            field=models.CharField(default='Чому ми', max_length=80, verbose_name='Підпис блоку'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_lead',
            field=models.TextField(default='П’ять причин, через які клієнти повертаються до нас знову і радять друзям', verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_title',
            field=models.CharField(default='Чому люди обирають обмінювати', max_length=160, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantagespage',
            name='why_title_accent',
            field=models.CharField(default='в Обмін21', max_length=80, verbose_name='Акцент у заголовку'),
        ),
    ]
