# Generated by Django 5.2.17 on 2026-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_advantages_page_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'Сторінка питань і відповідей', 'verbose_name_plural': 'Сторінка питань і відповідей'},
        ),
        migrations.AddField(
            model_name='faqpage',
            name='cta_phone',
            field=models.CharField(default='Зателефонувати', max_length=80, verbose_name='Кнопка телефону'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='cta_telegram',
            field=models.CharField(default='Написати в Telegram', max_length=80, verbose_name='Кнопка Telegram'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='cta_text',
            field=models.CharField(default='Консультант відповість на будь-яке питання щодня з 8:00 до 21:00.', max_length=320, verbose_name='Текст підказки'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='cta_title',
            field=models.CharField(default='Не знайшли', max_length=120, verbose_name='Заголовок підказки'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='cta_title_accent',
            field=models.CharField(default='відповідь?', max_length=80, verbose_name='Акцент підказки'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='kicker',
            field=models.CharField(default='Відповіді', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='lead',
            field=models.CharField(blank=True, default='Короткі відповіді на те, що найчастіше запитують перед обміном.', max_length=400, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_accent',
            field=models.CharField(blank=True, default='поширені запитання', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_lead',
            field=models.CharField(blank=True, max_length=400, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_lead',
            field=models.CharField(blank=True, max_length=400, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_articles',
            field=models.BooleanField(default=True, help_text='Статті беруться з розділу Блог.', verbose_name='Показувати блок на головній'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_faq',
            field=models.BooleanField(default=True, help_text='Питання беруться зі сторінки Питання і відповіді.', verbose_name='Показувати блок на головній'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_map',
            field=models.BooleanField(default=True, help_text='Відділення беруться зі сторінки Контакти.', verbose_name='Показувати блок на головній'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_reviews',
            field=models.BooleanField(default=True, help_text='Відгуки беруться зі сторінки Відгуки.', verbose_name='Показувати блок на головній'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_services',
            field=models.BooleanField(default=True, help_text='Картки — зі сторінки Послуги (позначка «Показувати на головній»).', verbose_name='Показувати блок на головній'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_why',
            field=models.BooleanField(default=True, help_text='Цифри беруться зі сторінки Переваги.', verbose_name='Показувати блок на головній'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='cta_button',
            field=models.CharField(default='Залишити відгук', max_length=80, verbose_name='Кнопка'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='kicker',
            field=models.CharField(default='Відгуки', max_length=80, verbose_name='Підпис над заголовком'),
        ),
        migrations.AddField(
            model_name='reviewspage',
            name='title_accent',
            field=models.CharField(default='клієнтів', max_length=80, verbose_name='Акцент у заголовку'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='title',
            field=models.CharField(default='Відповіді на', max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='reviewspage',
            name='intro',
            field=models.TextField(blank=True, default='Що кажуть люди, які вже обмінювали валюту в Обмін21.', verbose_name='Підзаголовок'),
        ),
    ]
