# Generated by Django 5.2.17 on 2026-09-24 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('text', models.TextField(verbose_name='Текст')),
                ('city_name', models.CharField(blank=True, max_length=80, verbose_name='Місто (текст)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('consent', models.BooleanField(default=False, verbose_name='Згода')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано о')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
