# Generated by Django 5.2.17 on 2026-10-05 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_cms_page_sections'),
        ('reviews', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='content.homepage', verbose_name='Головна'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка'),
        ),
    ]
