# Generated by Django 5.2.17 on 2026-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='figure',
            field=models.ImageField(blank=True, upload_to='blog/figure/', verbose_name='Картинка в статті'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='blog.post', verbose_name='Читати також'),
        ),
    ]
