# Generated by Django 5.2.17 on 2026-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cms_page_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_filter',
            field=models.BooleanField(default=True, verbose_name='Показувати у фільтрі на сторінці'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='Код у посиланні'),
        ),
        migrations.AlterField(
            model_name='post',
            name='faq',
            field=models.TextField(blank=True, verbose_name='Питання та відповіді (необовʼязково)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис у пошуку'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заголовок у пошуку'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Код у посиланні'),
        ),
    ]
