# Generated by Django 5.2.17 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_page_heading_and_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
    ]
