# Generated by Django 5.2.17 on 2026-09-24 12:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Slug')),
                ('base_code', models.CharField(default='UAH', max_length=8, verbose_name='Базова валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('intro', models.TextField(blank=True, verbose_name='Опис для сторінки пари')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Валютна пара',
                'verbose_name_plural': 'Валютні пари',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('retail', 'Роздріб'), ('wholesale', 'Опт'), ('cross', 'Крос'), ('crypto', 'Крипто')], default='retail', max_length=16, verbose_name='Дошка')),
                ('buy', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Купівля')),
                ('sell', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Продаж')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('city', models.ForeignKey(blank=True, help_text='Порожньо = глобальний курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='network.city', verbose_name='Місто')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='rates.currencypair', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['pair__sort_order', 'pair__code'],
                'constraints': [models.UniqueConstraint(fields=('pair', 'board', 'city'), name='uniq_quote_pair_board_city')],
            },
        ),
    ]
