# Generated by Django 5.2.17 on 2026-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='flag_image',
            field=models.ImageField(blank=True, help_text='Якщо порожньо — стандартний прапор за кодом валюти.', upload_to='flags/', verbose_name='Іконка прапора'),
        ),
    ]
