# Generated by Django 5.2.17 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_cms_page_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='Опис для SEO'),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Назва для SEO'),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Код у посиланні'),
        ),
    ]
