# Generated by Django 5.2.17 on 2026-10-05 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Chat ID')),
                ('state', models.CharField(default='idle', max_length=32, verbose_name='Стан FSM')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дані сценарію')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Сесія бота',
                'verbose_name_plural': 'Сесії бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name="Ім'я в Telegram")),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Прізвище в Telegram')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name="Ім'я для заявок")),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profiles', to='network.city', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Користувач бота',
                'verbose_name_plural': 'Користувачі бота',
                'ordering': ['-updated_at'],
            },
        ),
    ]
