# Generated by Django 5.2.17 on 2026-10-05 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_telegram_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=32, verbose_name='Chat ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('bot', 'Бот')], max_length=8, verbose_name='Роль')),
                ('text', models.TextField(verbose_name='Текст')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='Кнопки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Повідомлення чату',
                'ordering': ['created_at'],
            },
        ),
    ]
