# Generated by Django 5.2.17 on 2026-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Обмін21', max_length=120, verbose_name='Назва сайту')),
                ('logo_text', models.CharField(default='ОБМІН', max_length=40, verbose_name='Текст логотипу')),
                ('logo_accent', models.CharField(default='21', max_length=10, verbose_name='Акцент логотипу')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('rate_hold_minutes', models.PositiveIntegerField(default=30, verbose_name='Хвилин фіксації курсу')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Email сповіщень')),
                ('notify_telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat id')),
                ('default_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон за замовчуванням')),
                ('footer_copy', models.CharField(default='© 2021–2026 Обмін21', max_length=120, verbose_name='Копірайт')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
