# Generated by Django 5.2.17 on 2026-10-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал сайту',
                'verbose_name_plural': 'Підвал сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Загальні налаштування', 'verbose_name_plural': 'Загальні налаштування'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки підвалу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_color_bg',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону підвалу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_color_text',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту підвалу'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Якщо порожньо — лишається стандартний логотип.', upload_to='chrome/', verbose_name='Логотип у підвалі'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_color_accent',
            field=models.CharField(default='#ca8d42', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір підсвітки шапки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_color_bg',
            field=models.CharField(default='#ffffff', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір фону шапки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_color_text',
            field=models.CharField(default='#052145', help_text='Натисніть квадратик, щоб обрати колір. Зміна з’явиться на сайті після збереження.', max_length=7, validators=[django.core.validators.RegexValidator(message='Оберіть колір у палітрі.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту шапки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_logo',
            field=models.ImageField(blank=True, help_text='Якщо порожньо — лишається стандартний логотип.', upload_to='chrome/', verbose_name='Логотип у шапці'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон, якщо місто не обрано'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Посилання Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copy',
            field=models.CharField(default='© 2026. Обмін21. Усі права захищені', max_length=120, verbose_name='Рядок копірайту внизу'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Посилання Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для сповіщень'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер чату Telegram для сповіщень'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Посилання Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Посилання YouTube'),
        ),
    ]
