# Generated by Django 5.2.17 on 2026-09-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('hours', models.CharField(blank=True, max_length=120, verbose_name='Графік')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('map_url', models.URLField(blank=True, verbose_name='Посилання на карту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='network.city', verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Відділення',
                'verbose_name_plural': 'Відділення',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
