# Generated by Django 5.2.17 on 2026-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_city_home_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCity',
            fields=[
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банер',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('network.city',),
        ),
        migrations.CreateModel(
            name='ContactCity',
            fields=[
            ],
            options={
                'verbose_name': 'Адреси міст',
                'verbose_name_plural': 'Адреси міст',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('network.city',),
        ),
        migrations.CreateModel(
            name='MapCity',
            fields=[
            ],
            options={
                'verbose_name': 'Знайдіть нас на карті',
                'verbose_name_plural': 'Знайдіть нас на карті',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('network.city',),
        ),
        migrations.AddField(
            model_name='city',
            name='banner_button',
            field=models.CharField(default='Зафіксувати курс', max_length=80, verbose_name='Текст кнопки на банері'),
        ),
    ]
